language: python

python:
  - "2.7"

cache:
  pip : true
  directories:
    - $HOME/.cache

jobs:
  include :
    - stage: Prepare cache
      script: true
    - stage: Show directory contents
      script: ls -al
    - stage: Check for new releases
      script: python bin/release.py
    - stage: Upload to repository
      script:
        - chmod +x bin/upload.sh
        - bin/upload.sh
    - stage: Show new manifest.json
      script: cat manifest.json