language: python

python:
  - "2.7"

cache:
  pip : true
  directories:
    - $HOME/cache

jobs:
  include :
    - stage: Prepare cache
      script: true
    - stage: Check for new releases
      script:
        - ls -al
        - python bin/release.py
    - stage: Upload to repository
      script:
        - chmod +x bin/upload.sh
        - bin/upload.sh
        - cat manifest.json
