language: python

python:
  - "2.7"

cache:
  pip : true
  directories:
    - $HOME/cache

jobs:
  include :
    - stage: Check for new releases and upload
      script:
        - ls -al
        - python bin/release.py -u bin/upload.sh
        - cat manifest.json
